version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:7.2.1
    ports:
      - '6379:6379'
    networks:
      - basket

  mongodb:
    container_name: mongodb
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - catalog

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.18
    restart: always
    volumes:
      - ./apps/discount/src/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      - discount
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  mysql:
    container_name: mysql
    image: mysql:8.0.36-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    networks:
      - order
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

networks:
  basket:
  catalog:
  discount:
  order:
