version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - catalog

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.18
    restart: always
    volumes:
      - ./apps/discount/src/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      - discount
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  catalog:
  discount:
